name: Node CI

on: 
  push:
    branches:
      - master
    tags:
      - "*.*.*"

jobs:
  build:
    strategy:
      matrix:
        include:
         - os: windows-latest
           platform: win32
           arch: x64
           npm_config_arch: x64
           target: win32-x64
         - os: ubuntu-latest
           platform: linux
           arch: x64
           npm_config_arch: x64
           target: linux-x64
         - os: macos-latest
           platform: darwin
           arch: x64
           npm_config_arch: x64
           target: darwin-x64
         - os: macos-latest
           platform: darwin
           arch: arm64
           npm_config_arch: arm64
           target: darwin-arm64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set node 20.x
      uses: actions/setup-node@v6
      with:
          node-version: 20.x
    - name: Install
      uses: borales/actions-yarn@v4
      with: 
        cmd: install
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        npm_config_arch: ${{ matrix.npm_config_arch }}      
    - name: build
      run: |
        node ./build/prepare.js ${{ matrix.target }}
        npx vsce package --target ${{ matrix.target }}
    - name: Upload
      uses: actions/upload-artifact@v4
      with: 
        name: ${{ matrix.target }}
        path: ${{ github.workspace }}/emmylua-unity*.vsix
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
      - run: npx  vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
