name: Node CI

on: 
  push:
    branches:
      - master
    tags:
      - "*.*.*"

jobs:
  build:
    strategy:
      matrix:
        include:
         - os: windows-latest
           platform: win32
           arch: x64
           npm_config_arch: x64
         - os: ubuntu-latest
           platform: linux
           arch: x64
           npm_config_arch: x64
         - os: macos-latest
           platform: darwin
           arch: x64
           npm_config_arch: x64
         - os: macos-latest
           platform: darwin
           arch: arm64
           npm_config_arch: arm64

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
    - name: npm install
      run: npm i
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       npm_config_arch: ${{ matrix.npm_config_arch }}
    - name: set env variable
      run: echo "target=${{ matrix.platform }}-${{ matrix.arch }}" >> $GITHUB_ENV
    - name: build
      run: |
        node ./build/prepare.js ${{ env.target }}
        mkdir -p server/bin
        cp temp/server/${{ env.target }}/bin/CodeFormatServer* server/bin/
        npx vsce package --target ${{ env.target }}
    - name: Upload
      uses: actions/upload-artifact@v2
      with: 
        name: ${{ env.target }}
        path: ${{ github.workspace }}/emmylua-codestyle*.vsix
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v2
      - run: npx  vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
